# run_local.ps1 - Local development runner (PowerShell)


param(
    [switch]$Test,
    [switch]$Coverage
)


# ===== CHECK VIRTUAL ENVIRONMENT =====
if (-not $env:VIRTUAL_ENV) {
    Write-Host "⚠️  Virtual environment not activated. Activating..." -ForegroundColor Yellow

    if (Test-Path "venv\Scripts\Activate.ps1") {
        & ".\venv\Scripts\Activate.ps1"
        Write-Host "✅ Virtual environment activated" -ForegroundColor Green
    } elseif (Test-Path ".venv\Scripts\Activate.ps1") {
        & ".\.venv\Scripts\Activate.ps1"
        Write-Host "✅ Virtual environment activated" -ForegroundColor Green
    } else {
        Write-Host "❌ No virtual environment found (venv or .venv)!" -ForegroundColor Red
        Write-Host "   Run: python -m venv venv" -ForegroundColor Yellow
        exit 1
    }
    Write-Host ""
}


# ===== TEST MODE =====
if ($Test) {
    Write-Host "🧪 Running tests..." -ForegroundColor Yellow

    if ($Coverage) {
        pytest tests/ -v --cov=huawei_solar_modbus_mqtt/modbus_energy_meter --cov-report=html
        if ($LASTEXITCODE -eq 0) {
            Write-Host "✅ All tests passed!" -ForegroundColor Green
            Write-Host "📊 Opening coverage report..." -ForegroundColor Cyan
            start htmlcov/index.html
        } else {
            Write-Host "❌ Tests failed!" -ForegroundColor Red
        }
    } else {
        pytest tests/ -v
        if ($LASTEXITCODE -eq 0) {
            Write-Host "✅ All tests passed!" -ForegroundColor Green
        } else {
            Write-Host "❌ Tests failed!" -ForegroundColor Red
        }
    }

    exit $LASTEXITCODE
}


# ===== NORMAL MODE =====
Write-Host "========================================================================" -ForegroundColor Cyan
Write-Host "🚀 huABus - Local Development" -ForegroundColor Green
Write-Host "========================================================================" -ForegroundColor Cyan


# Load .env (besseres Parsing)
if (Test-Path .env) {
    Write-Host "📄 Loading .env" -ForegroundColor Blue
    Get-Content .env | ForEach-Object {
        $line = $_.Trim()
        # Skip comments and empty lines
        if ($line -and !$line.StartsWith('#')) {
            if ($line -match '^([^=]+)=(.*)$') {
                $key = $matches[1].Trim()
                $value = $matches[2].Trim()
                Set-Item -Path "env:$key" -Value $value
                Write-Host "  $key = $value" -ForegroundColor DarkGray
            }
        }
    }
} else {
    Write-Host "❌ No .env file!" -ForegroundColor Red
    exit 1
}


Write-Host ""
Write-Host "========================================================================" -ForegroundColor Cyan
Write-Host ">> System Info:" -ForegroundColor Blue


# Python version
$pythonVersion = python --version 2>&1 | Select-String -Pattern "Python (\d+\.\d+\.\d+)" | ForEach-Object { $_.Matches.Groups[1].Value }
Write-Host "   - Python: $pythonVersion" -ForegroundColor White


# Get version from __version__.py (generated by update_version.py)
try {
    $versionPath = "huawei_solar_modbus_mqtt\modbus_energy_meter\__version__.py"
    if (Test-Path $versionPath) {
        $versionContent = Get-Content $versionPath | Select-String '__version__\s*=\s*"([^"]+)"'
        if ($versionContent) {
            $addonVersion = $versionContent.Matches.Groups[1].Value
            Write-Host "   [DEBUG] Found __version__.py: $addonVersion" -ForegroundColor DarkGray
        } else {
            $addonVersion = "dev"
            Write-Host "   [DEBUG] Could not parse __version__ from file" -ForegroundColor DarkYellow
        }
    } else {
        $addonVersion = "dev"
        Write-Host "   [DEBUG] __version__.py not found (Path: $versionPath)" -ForegroundColor DarkYellow
    }
} catch {
    $addonVersion = "dev"
    Write-Host "   [DEBUG] Error reading __version__.py: $_" -ForegroundColor Red
}

Write-Host "   - Addon Version: $addonVersion" -ForegroundColor Cyan


# Package versions
try {
    $huaweiVersion = pip show huawei-solar 2>$null | Select-String "^Version:" | ForEach-Object { $_.ToString().Split(":")[1].Trim() }
    if (!$huaweiVersion) { $huaweiVersion = "unknown" }
} catch { $huaweiVersion = "unknown" }


try {
    $pymodbusVersion = pip show pymodbus 2>$null | Select-String "^Version:" | ForEach-Object { $_.ToString().Split(":")[1].Trim() }
    if (!$pymodbusVersion) { $pymodbusVersion = "unknown" }
} catch { $pymodbusVersion = "unknown" }


try {
    $pahoVersion = pip show paho-mqtt 2>$null | Select-String "^Version:" | ForEach-Object { $_.ToString().Split(":")[1].Trim() }
    if (!$pahoVersion) { $pahoVersion = "unknown" }
} catch { $pahoVersion = "unknown" }


Write-Host "   - huawei-solar: $huaweiVersion" -ForegroundColor White
Write-Host "   - pymodbus: $pymodbusVersion" -ForegroundColor White
Write-Host "   - paho-mqtt: $pahoVersion" -ForegroundColor White


Write-Host "========================================================================" -ForegroundColor Cyan
Write-Host ">> Configuration:" -ForegroundColor Blue
Write-Host "   🔌 Inverter: $env:HUAWEI_MODBUS_HOST`:$env:HUAWEI_MODBUS_PORT (Slave ID: $env:HUAWEI_SLAVE_ID)" -ForegroundColor White
Write-Host "   📡 MQTT:     $env:HUAWEI_MODBUS_MQTT_BROKER`:$env:HUAWEI_MODBUS_MQTT_PORT" -ForegroundColor White
Write-Host "   📍 Topic:    $env:HUAWEI_MODBUS_MQTT_TOPIC" -ForegroundColor White
Write-Host "   ⏱️  Poll:     $env:HUAWEI_POLL_INTERVAL`s | Timeout: $env:HUAWEI_STATUS_TIMEOUT`s" -ForegroundColor White
Write-Host "   📍 Log:      $env:HUAWEI_LOG_LEVEL" -ForegroundColor White
Write-Host "========================================================================" -ForegroundColor Cyan


# Check if MQTT broker is reachable
$mqttHost = $env:HUAWEI_MODBUS_MQTT_BROKER
$mqttPort = $env:HUAWEI_MODBUS_MQTT_PORT
try {
    $connection = Test-NetConnection -ComputerName $mqttHost -Port $mqttPort -WarningAction SilentlyContinue
    if (!$connection.TcpTestSucceeded) {
        Write-Host "⚠️  MQTT Broker not reachable at ${mqttHost}:${mqttPort}" -ForegroundColor Yellow
        Write-Host "   Make sure Mosquitto is running!" -ForegroundColor Yellow
    } else {
        Write-Host "✅ MQTT Broker reachable" -ForegroundColor Green
    }
} catch {
    Write-Host "⚠️  Cannot test MQTT connection" -ForegroundColor Yellow
}


Write-Host ""
Write-Host ">> Starting Python application..." -ForegroundColor Blue
Write-Host "========================================================================" -ForegroundColor Cyan
Write-Host ""


# Run
Set-Location huawei_solar_modbus_mqtt
python -m modbus_energy_meter.main
