name: Bug Report
description: Report a bug or issue with the Huawei Solar MQTT Bridge
title: "[BUG] "
labels: ["bug", "triage"]
assignees: []

body:
  - type: markdown
    attributes:
      value: |
        Thanks for taking the time to report this issue! Please fill out the following information.

  - type: checkboxes
    id: prerequisites
    attributes:
      label: Prerequisites
      description: Please confirm the following before submitting
      options:
        - label: I have read the [documentation](blob/main/huawei_solar_modbus_mqtt/DOCS.md)
          required: true
        - label: I have searched existing issues to avoid duplicates
          required: true
        - label: I am using the latest version
          required: true

  - type: input
    id: version
    attributes:
      label: Version
      description: What version of the add-on are you using?
      placeholder: "e.g., 1.3.4"
    validations:
      required: true

  - type: input
    id: inverter-model
    attributes:
      label: Inverter Model
      description: Which Huawei inverter model are you using?
      placeholder: "e.g., SUN2000-6KTL-M1"
    validations:
      required: true

  - type: textarea
    id: description
    attributes:
      label: Bug Description
      description: Clear description of the bug
      placeholder: What happened? What did you expect to happen?
    validations:
      required: true

  - type: textarea
    id: reproduction
    attributes:
      label: Steps to Reproduce
      description: How can we reproduce this issue?
      placeholder: |
        1. Configure with...
        2. Start the add-on...
        3. See error...
    validations:
      required: true

  - type: textarea
    id: logs
    attributes:
      label: Relevant Logs
      description: Please paste relevant log excerpts (set `HUAWEI_LOG_LEVEL=DEBUG` for detailed logs)
      render: shell
    validations:
      required: true

  - type: textarea
    id: config
    attributes:
      label: Configuration
      description: Your add-on configuration (remove sensitive data like IP addresses)
      render: yaml
    validations:
      required: false

  - type: dropdown
    id: installation
    attributes:
      label: Installation Type
      options:
        - Home Assistant Add-on
        - Docker Container
        - Python standalone
    validations:
      required: true

  - type: textarea
    id: additional
    attributes:
      label: Additional Context
      description: Any other relevant information
    validations:
      required: false
