from typing import Dict, Any, List

NUMERIC_SENSORS: List[Dict[str, Any]] = [
    # === Core Power Values (immer vorhanden) ===
    {
        "name": "Solar Power",
        "key": "power_active",
        "unit_of_measurement": "W",
        "device_class": "power",
        "state_class": "measurement",
        "icon": "mdi:solar-power",
        "enabled": True,
    },
    {
        "name": "Input Power",
        "key": "power_input",
        "unit_of_measurement": "W",
        "device_class": "power",
        "state_class": "measurement",
        "icon": "mdi:solar-panel",
        "enabled": True,
    },
    {
        "name": "Grid Power",
        "key": "meter_power_active",
        "unit_of_measurement": "W",
        "device_class": "power",
        "state_class": "measurement",
        "icon": "mdi:transmission-tower",
        "enabled": True,
    },
    {
        "name": "Battery Power",
        "key": "battery_power",
        "unit_of_measurement": "W",
        "device_class": "power",
        "state_class": "measurement",
        "icon": "mdi:battery-charging",
        "value_template": "{{ value_json.battery_power | default(0) }}",
        "enabled": True,
    },

    # === Energy Values ===
    {
        "name": "Solar Daily Yield",
        "key": "energy_yield_day",
        "unit_of_measurement": "kWh",
        "device_class": "energy",
        "state_class": "total_increasing",
        "icon": "mdi:solar-power",
        "enabled": True,
    },
    {
        "name": "Solar Total Yield",
        "key": "energy_yield_accumulated",
        "unit_of_measurement": "kWh",
        "device_class": "energy",
        "state_class": "total_increasing",
        "icon": "mdi:solar-power",
        "enabled": True,
    },
    {
        "name": "Grid Energy Exported",
        "key": "energy_grid_exported",
        "unit_of_measurement": "kWh",
        "device_class": "energy",
        "state_class": "total_increasing",
        "icon": "mdi:transmission-tower-export",
        "value_template": "{{ value_json.energy_grid_exported | default(0) }}",
        "enabled": True,
    },
    # === Raw value ===
    {
        "name": "Grid Energy Exported (Raw)",
        "key": "energy_grid_exported_raw",
        "unit_of_measurement": "kWh",
        "device_class": "energy",
        "state_class": "total_increasing",
        "icon": "mdi:transmission-tower-export",
        "value_template": "{{ value_json.energy_grid_exported_raw | default(0) }}",
        "enabled": False,
        "entity_category": "diagnostic",
    },
    {
        "name": "Grid Energy Imported",
        "key": "energy_grid_accumulated",
        "unit_of_measurement": "kWh",
        "device_class": "energy",
        "state_class": "total_increasing",
        "icon": "mdi:transmission-tower-import",
        "enabled": True,
    },

    # === Battery (alle optional) ===
    {
        "name": "Battery SOC",
        "key": "battery_soc",
        "unit_of_measurement": "%",
        "device_class": "battery",
        "state_class": "measurement",
        "icon": "mdi:battery",
        "value_template": "{{ value_json.battery_soc | default(0) }}",
        "enabled": True,
    },
    {
        "name": "Battery Charge Today",
        "key": "battery_charge_day",
        "unit_of_measurement": "kWh",
        "device_class": "energy",
        "state_class": "total_increasing",
        "icon": "mdi:battery-plus",
        "value_template": "{{ value_json.battery_charge_day | default(0) }}",
        "enabled": True,
    },
    {
        "name": "Battery Discharge Today",
        "key": "battery_discharge_day",
        "unit_of_measurement": "kWh",
        "device_class": "energy",
        "state_class": "total_increasing",
        "icon": "mdi:battery-minus",
        "value_template": "{{ value_json.battery_discharge_day | default(0) }}",
        "enabled": True,
    },
    {
        "name": "Battery Total Charge",
        "key": "battery_charge_total",
        "unit_of_measurement": "kWh",
        "device_class": "energy",
        "state_class": "total_increasing",
        "value_template": "{{ value_json.battery_charge_total | default(0) }}",
        "enabled": True,
    },
    {
        "name": "Battery Total Discharge",
        "key": "battery_discharge_total",
        "unit_of_measurement": "kWh",
        "device_class": "energy",
        "state_class": "total_increasing",
        "value_template": "{{ value_json.battery_discharge_total | default(0) }}",
        "enabled": True,
    },
    {
        "name": "Battery Bus Voltage",
        "key": "battery_bus_voltage",
        "unit_of_measurement": "V",
        "device_class": "voltage",
        "state_class": "measurement",
        "value_template": "{{ value_json.battery_bus_voltage | default(0) }}",
        "enabled": True,
    },
    {
        "name": "Battery Bus Current",
        "key": "battery_bus_current",
        "unit_of_measurement": "A",
        "device_class": "current",
        "state_class": "measurement",
        "value_template": "{{ value_json.battery_bus_current | default(0) }}",
        "enabled": True,
    },

    # === PV Strings (alle optional, nachts = 0) ===
    {
        "name": "PV1 Voltage",
        "key": "voltage_PV1",
        "unit_of_measurement": "V",
        "device_class": "voltage",
        "state_class": "measurement",
        "value_template": "{{ value_json.voltage_PV1 | default(0) }}",
        "enabled": True,
    },
    {
        "name": "PV1 Current",
        "key": "current_PV1",
        "unit_of_measurement": "A",
        "device_class": "current",
        "state_class": "measurement",
        "value_template": "{{ value_json.current_PV1 | default(0) }}",
        "enabled": True,
    },
    {
        "name": "PV2 Voltage",
        "key": "voltage_PV2",
        "unit_of_measurement": "V",
        "device_class": "voltage",
        "state_class": "measurement",
        "value_template": "{{ value_json.voltage_PV2 | default(0) }}",
        "enabled": False,
    },
    {
        "name": "PV2 Current",
        "key": "current_PV2",
        "unit_of_measurement": "A",
        "device_class": "current",
        "state_class": "measurement",
        "value_template": "{{ value_json.current_PV2 | default(0) }}",
        "enabled": False,
    },
    {
        "name": "PV3 Voltage",
        "key": "voltage_PV3",
        "unit_of_measurement": "V",
        "device_class": "voltage",
        "state_class": "measurement",
        "value_template": "{{ value_json.voltage_PV3 | default(0) }}",
        "enabled": False,
    },
    {
        "name": "PV3 Current",
        "key": "current_PV3",
        "unit_of_measurement": "A",
        "device_class": "current",
        "state_class": "measurement",
        "value_template": "{{ value_json.current_PV3 | default(0) }}",
        "enabled": False,
    },
    {
        "name": "PV4 Voltage",
        "key": "voltage_PV4",
        "unit_of_measurement": "V",
        "device_class": "voltage",
        "state_class": "measurement",
        "value_template": "{{ value_json.voltage_PV4 | default(0) }}",
        "enabled": False,
    },
    {
        "name": "PV4 Current",
        "key": "current_PV4",
        "unit_of_measurement": "A",
        "device_class": "current",
        "state_class": "measurement",
        "value_template": "{{ value_json.current_PV4 | default(0) }}",
        "enabled": False,
    },

    # === Inverter Diagnostics ===
    {
        "name": "Inverter Temperature",
        "key": "inverter_temperature",
        "unit_of_measurement": "°C",
        "device_class": "temperature",
        "state_class": "measurement",
        "value_template": "{{ value_json.inverter_temperature | default(0) }}",
        "enabled": True,
        "entity_category": "diagnostic",
    },
    {
        "name": "Inverter Efficiency",
        "key": "inverter_efficiency",
        "unit_of_measurement": "%",
        "state_class": "measurement",
        "icon": "mdi:gauge",
        "value_template": "{{ value_json.inverter_efficiency | default(0) }}",
        "enabled": True,
    },
    {
        "name": "Day Peak Power",
        "key": "power_active_peak_day",
        "unit_of_measurement": "W",
        "device_class": "power",
        "state_class": "measurement",
        "value_template": "{{ value_json.power_active_peak_day | default(0) }}",
        "enabled": True,
    },
    {
        "name": "Reactive Power",
        "key": "power_reactive",
        "unit_of_measurement": "var",
        "device_class": "reactive_power",
        "state_class": "measurement",
        "value_template": "{{ value_json.power_reactive | default(0) }}",
        "enabled": True,
    },
    {
        "name": "Power Factor",
        "key": "power_factor",
        "unit_of_measurement": "",
        "state_class": "measurement",
        "icon": "mdi:sine-wave",
        "value_template": "{{ value_json.power_factor | default(0) }}",
        "enabled": True,
    },
    {
        "name": "Insulation Resistance",
        "key": "inverter_insulation_resistance",
        "unit_of_measurement": "MΩ",
        "state_class": "measurement",
        "icon": "mdi:lightning-bolt-circle",
        "value_template": "{{ value_json.inverter_insulation_resistance | default(0) }}",
        "enabled": True,
        "entity_category": "diagnostic",
    },

    # === Grid Voltages (3-Phasen System, evtl. nur Phase A bei 1-Phasen) ===
    {
        "name": "Grid Voltage Phase A",
        "key": "voltage_grid_A",
        "unit_of_measurement": "V",
        "device_class": "voltage",
        "state_class": "measurement",
        "value_template": "{{ value_json.voltage_grid_A | default(0) }}",
        "enabled": True,
    },
    {
        "name": "Grid Voltage Phase B",
        "key": "voltage_grid_B",
        "unit_of_measurement": "V",
        "device_class": "voltage",
        "state_class": "measurement",
        "value_template": "{{ value_json.voltage_grid_B | default(0) }}",
        "enabled": True,
    },
    {
        "name": "Grid Voltage Phase C",
        "key": "voltage_grid_C",
        "unit_of_measurement": "V",
        "device_class": "voltage",
        "state_class": "measurement",
        "value_template": "{{ value_json.voltage_grid_C | default(0) }}",
        "enabled": True,
    },
    {
        "name": "Line Voltage A-B",
        "key": "voltage_line_AB",
        "unit_of_measurement": "V",
        "device_class": "voltage",
        "state_class": "measurement",
        "value_template": "{{ value_json.voltage_line_AB | default(0) }}",
        "enabled": True,
    },
    {
        "name": "Line Voltage B-C",
        "key": "voltage_line_BC",
        "unit_of_measurement": "V",
        "device_class": "voltage",
        "state_class": "measurement",
        "value_template": "{{ value_json.voltage_line_BC | default(0) }}",
        "enabled": True,
    },
    {
        "name": "Line Voltage C-A",
        "key": "voltage_line_CA",
        "unit_of_measurement": "V",
        "device_class": "voltage",
        "state_class": "measurement",
        "value_template": "{{ value_json.voltage_line_CA | default(0) }}",
        "enabled": True,
    },
    {
        "name": "Grid Frequency",
        "key": "frequency_grid",
        "unit_of_measurement": "Hz",
        "device_class": "frequency",
        "state_class": "measurement",
        "value_template": "{{ value_json.frequency_grid | default(50) }}",
        "enabled": True,
    },

    # === Meter Values ===
    {
        "name": "Meter Reactive Power",
        "key": "meter_reactive_power",
        "unit_of_measurement": "var",
        "device_class": "reactive_power",
        "state_class": "measurement",
        "value_template": "{{ value_json.meter_reactive_power | default(0) }}",
        "enabled": True,
    },
    {
        "name": "Meter Power Phase A",
        "key": "power_meter_A",
        "unit_of_measurement": "W",
        "device_class": "power",
        "state_class": "measurement",
        "icon": "mdi:transmission-tower",
        "value_template": "{{ value_json.power_meter_A | default(0) }}",
        "enabled": True,
    },
    {
        "name": "Meter Power Phase B",
        "key": "power_meter_B",
        "unit_of_measurement": "W",
        "device_class": "power",
        "state_class": "measurement",
        "icon": "mdi:transmission-tower",
        "value_template": "{{ value_json.power_meter_B | default(0) }}",
        "enabled": True,
    },
    {
        "name": "Meter Power Phase C",
        "key": "power_meter_C",
        "unit_of_measurement": "W",
        "device_class": "power",
        "state_class": "measurement",
        "icon": "mdi:transmission-tower",
        "value_template": "{{ value_json.power_meter_C | default(0) }}",
        "enabled": True,
    },
    {
        "name": "Meter Line Voltage A-B",
        "key": "voltage_meter_line_AB",
        "unit_of_measurement": "V",
        "device_class": "voltage",
        "state_class": "measurement",
        "value_template": "{{ value_json.voltage_meter_line_AB | default(0) }}",
        "enabled": True,
    },
    {
        "name": "Meter Line Voltage B-C",
        "key": "voltage_meter_line_BC",
        "unit_of_measurement": "V",
        "device_class": "voltage",
        "state_class": "measurement",
        "value_template": "{{ value_json.voltage_meter_line_BC | default(0) }}",
        "enabled": True,
    },
    {
        "name": "Meter Line Voltage C-A",
        "key": "voltage_meter_line_CA",
        "unit_of_measurement": "V",
        "device_class": "voltage",
        "state_class": "measurement",
        "value_template": "{{ value_json.voltage_meter_line_CA | default(0) }}",
        "enabled": True,
    },
    {
        "name": "Meter Current Phase A",
        "key": "current_meter_A",
        "unit_of_measurement": "A",
        "device_class": "current",
        "state_class": "measurement",
        "value_template": "{{ value_json.current_meter_A | default(0) }}",
        "enabled": True,
    },
    {
        "name": "Meter Current Phase B",
        "key": "current_meter_B",
        "unit_of_measurement": "A",
        "device_class": "current",
        "state_class": "measurement",
        "value_template": "{{ value_json.current_meter_B | default(0) }}",
        "enabled": True,
    },
    {
        "name": "Meter Current Phase C",
        "key": "current_meter_C",
        "unit_of_measurement": "A",
        "device_class": "current",
        "state_class": "measurement",
        "value_template": "{{ value_json.current_meter_C | default(0) }}",
        "enabled": True,
    },
    {
        "name": "Meter Frequency",
        "key": "frequency_meter",
        "unit_of_measurement": "Hz",
        "device_class": "frequency",
        "state_class": "measurement",
        "value_template": "{{ value_json.frequency_meter | default(50) }}",
        "enabled": True,
    },
    {
        "name": "Meter Power Factor",
        "key": "power_factor_meter",
        "unit_of_measurement": "",
        "state_class": "measurement",
        "icon": "mdi:sine-wave",
        "value_template": "{{ value_json.power_factor_meter | default(0) }}",
        "enabled": True,
    },

    # === Static Device Info ===
    {
        "name": "Rated Power",
        "key": "rated_power",
        "unit_of_measurement": "W",
        "device_class": "power",
        "state_class": "measurement",
        "icon": "mdi:gauge",
        "enabled": True,
        "entity_category": "diagnostic",
    },
]

TEXT_SENSORS: List[Dict[str, Any]] = [
    {
        "name": "Inverter Status",
        "key": "inverter_status",
        "icon": "mdi:information",
        "value_template": "{{ value_json.inverter_status | default('unknown') }}",
        "enabled": True,
        "entity_category": "diagnostic",
    },
    {
        "name": "Battery Status",
        "key": "battery_status",
        "icon": "mdi:battery-heart",
        "value_template": "{{ value_json.battery_status | default('unknown') }}",
        "enabled": True,
        "entity_category": "diagnostic",
    },
    {
        "name": "Meter Status",
        "key": "meter_status",
        "icon": "mdi:meter-electric",
        "value_template": "{{ value_json.meter_status | default('unknown') }}",
        "enabled": True,
        "entity_category": "diagnostic",
    },
    {
        "name": "Model Name",
        "key": "model_name",
        "icon": "mdi:information",
        "value_template": "{{ value_json.model_name | default('N/A') }}",
        "enabled": True,
        "entity_category": "diagnostic",
    },
    {
        "name": "Serial Number",
        "key": "serial_number",
        "icon": "mdi:barcode",
        "value_template": "{{ value_json.serial_number | default('N/A') }}",
        "enabled": True,
        "entity_category": "diagnostic",
    },
    {
        "name": "Inverter State 1",
        "key": "inverter_state_1",
        "value_template": "{{ value_json.inverter_state_1 | default('') }}",
        "enabled": False,
        "entity_category": "diagnostic",
    },
    {
        "name": "Inverter State 2",
        "key": "inverter_state_2",
        "value_template": "{{ value_json.inverter_state_2 | default('') }}",
        "enabled": False,
        "entity_category": "diagnostic",
    },
    {
        "name": "Inverter Startup Time",
        "key": "startup_time",
        "device_class": "timestamp",
        "value_template": "{{ value_json.startup_time | default(None) }}",
        "enabled": False,
        "entity_category": "diagnostic",
    },
]
